In [1]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import random
import numpy as np

/home/milad/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# load iris

In [3]:
# save "bunch" object containing iris dataset and its attributes
iris = load_iris()


# store feature matrix in "X"# store  
X = iris.data

# store response vector in "y"
y = iris.target

x_train_iris, x_test_iris, y_train_iris, y_test_iris = train_test_split(X, y, test_size=0.2, random_state=4)

#classifier
mnb = MultinomialNB()
mnb.fit(x_train_iris,y_train_iris)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

# Accuracy on test data

In [6]:
y_pred=mnb.predict(x_test_iris)


print ("Accuracy on test data is {}".format(accuracy_score(y_test_iris, y_pred)))
confusion_matrix(y_test_iris, y_pred)

Accuracy on test data is 0.8666666666666667


array([[16,  0,  0],
       [ 0,  5,  0],
       [ 0,  4,  5]])

# check all the combination

In [14]:
def combinations_index(iterable, r):
    # combinations('ABCD', 2) --> AB AC AD BC BD CD
    # combinations(range(4), 3) --> 012 013 023 123
    pool = tuple(iterable)
    n = len(pool)
    if r > n:
        return
    indices = list(range(r))
    yield list(indices)
    
    while True:
        for i in reversed(range(r)):
            if indices[i] != i + n - r:
                break
        else:
            return
        indices[i] += 1

        for j in range(i+1, r):
            indices[j] = indices[j-1] + 1
        yield list(indices)
        
        

def check_all_combination(x_train,y_train,percetage,mnb,change_plan):
    number_change_requested = int(percetage/100*x_train.shape[0])
    print("{} percentage error is equal to {} change \n".format(percetage,number_change_requested))
    
    used_row=[]
    occurred_change = 0
    all_changed = 1
    change_done=False
    x_train_changed = np.copy(x_train)
    
    for i in range(len(change_plan["key"])):
        occurred_change = 0
        
        indices = [t for t, x in enumerate(y_train) if x == change_plan["key"][i][0]]
        print("{} rows have target {} \n".format(len(indices),change_plan["key"][i][0]))
        
        
        for p in range (len(indices)):
            if (all_changed == number_change_requested +1):
                print("your requests have been done :)")
                break
            if y_train[indices[p]] == mnb.predict([x_train[indices[p]]])  and  indices[p] not in used_row :
                

                change_done=False
                for L in range(0, len(x_train_changed[indices[p]])+1):
                    if change_done:

                        break
                    else:
                        for subset in combinations_index(x_train_changed[indices[p]], L):
                            if not subset:
                                pass
                            else:

                                x_train_changed[indices[p]][subset] = 0

                                if (change_plan["key"][i][1] == mnb.predict([x_train_changed[indices[p]]])[0]):

                                    print(x_train[indices[p]],mnb.predict([x_train[indices[p]]])[0])
                                    print(x_train_changed[indices[p]],mnb.predict([x_train_changed[indices[p]]])[0])
                                    print(" \n change number {} \n".format(all_changed))
                                    
                                    used_row.append(indices[p])
                                    occurred_change=occurred_change + 1
                                    change_done=True
                                    all_changed=all_changed + 1
                                    break

                                else:
                                    x_train_changed[indices[p]]= np.copy(x_train[indices[p]])

    if (all_changed<=number_change_requested):
        print("your request doesn't complete! please change your plan")
    return np.copy(x_train_changed)






def check_all_combination_change_plan(x_train,y_train,percetage,mnb,change_plan):
    number_change_requested = int(percetage/100*x_train.shape[0])
    print("{} percentage error is equal to {} change \n".format(percetage,number_change_requested))
    
    used_row=[]
    occurred_change = 0
    all_changed = 1
    change_done=False
    x_train_changed = np.copy(x_train)
    
    for i in range(len(change_plan["key"])):
        occurred_change = 0
        
        indices = [t for t, x in enumerate(y_train) if x == change_plan["key"][i][0]]
        print("{} rows have target {} \n".format(len(indices),change_plan["key"][i][0]))
        
        
        for p in range (len(indices)):
            if (all_changed == number_change_requested +1):
                print("your requests have been done :)")
                break
            if (occurred_change == change_plan["number"][i]):
                print("part of your request has been done!")
                break
                
                
            if y_train[indices[p]] == mnb.predict([x_train[indices[p]]])  and  indices[p] not in used_row :
                

                change_done=False
                for L in range(0, len(x_train_changed[indices[p]])+1):
                    if change_done:

                        break
                    else:
                        for subset in combinations_index(x_train_changed[indices[p]], L):
                            if not subset:
                                pass
                            else:

                                x_train_changed[indices[p]][subset] = 0

                                if (change_plan["key"][i][1] == mnb.predict([x_train_changed[indices[p]]])[0]):

                                    print(x_train[indices[p]],mnb.predict([x_train[indices[p]]])[0])
                                    print(x_train_changed[indices[p]],mnb.predict([x_train_changed[indices[p]]])[0])
                                    print(" \n change number {} \n".format(all_changed))
                                    
                                    used_row.append(indices[p])
                                    occurred_change=occurred_change + 1
                                    change_done=True
                                    all_changed=all_changed + 1
                                    break

                                else:
                                    x_train_changed[indices[p]]= np.copy(x_train[indices[p]])

    if (all_changed<=number_change_requested):
        print("your request doesn't complete! please change your plan")
    return np.copy(x_train_changed)



# -10% - iris test data

In [34]:
import time
start = time.time()

change_plan={"key":[[0,2],[1,2]],"number":[5,4]}
new_check_all_combination_change_plan=check_all_combination_change_plan(x_test_iris,y_test_iris,30,mnb,change_plan)
end = time.time()
print("-----------------------------------------------------------")

print("\n your execuation time is {} \n".format(end - start))

print("-----------------------------------------------------------")
y_new_check_all_combination_change_plan =mnb.predict(new_check_all_combination_change_plan)

print ("Accuracy is {}".format(accuracy_score(y_test_iris, y_new_check_all_combination_change_plan)))
confusion_matrix(y_test_iris,y_new_check_all_combination_change_plan)

30 percentage error is equal to 9 change 

16 rows have target 0 

[ 5.7  3.8  1.7  0.3] 0
[ 0.   0.   1.7  0.3] 2
 
 change number 1 

[ 5.8  4.   1.2  0.2] 0
[ 0.   0.   1.2  0.2] 2
 
 change number 2 

[ 5.4  3.9  1.7  0.4] 0
[ 0.   0.   1.7  0.4] 2
 
 change number 3 

[ 5.   3.   1.6  0.2] 0
[ 0.   0.   1.6  0.2] 2
 
 change number 4 

[ 4.8  3.4  1.6  0.2] 0
[ 0.   0.   1.6  0.2] 2
 
 change number 5 

part of your request has been done!
5 rows have target 1 

[ 6.   2.9  4.5  1.5] 1
[ 0.   2.9  4.5  1.5] 2
 
 change number 6 

[ 6.   2.7  5.1  1.6] 1
[ 0.   2.7  5.1  1.6] 2
 
 change number 7 

[ 6.1  2.9  4.7  1.4] 1
[ 0.   2.9  4.7  1.4] 2
 
 change number 8 

[ 5.   2.   3.5  1. ] 1
[ 0.   2.   3.5  1. ] 2
 
 change number 9 

your requests have been done :)
-----------------------------------------------------------

 your execuation time is 0.020712614059448242 

-----------------------------------------------------------
Accuracy is 0.5666666666666667


array([[11,  0,  5],
       [ 0,  1,  4],
       [ 0,  4,  5]])

# -10% - iris train data 

In [32]:
import time
start = time.time()

change_plan={"key":[[0,2],[1,2]],"number":[18,18]}
out_train_10_iris=check_all_combination_change_plan(x_train_iris,y_train_iris,30,mnb,change_plan)
end = time.time()
print("-----------------------------------------------------------")

print("\n your execuation time is {} \n".format(end - start))

print("-----------------------------------------------------------")
y_out_train_10_iris = mnb.predict(out_train_10_iris)

print ("Accuracy is {}".format(accuracy_score(y_train_iris, y_out_train_10_iris)))
confusion_matrix(y_train_iris, y_out_train_10_iris)

30 percentage error is equal to 36 change 

34 rows have target 0 

[ 4.6  3.2  1.4  0.2] 0
[ 0.   0.   1.4  0.2] 2
 
 change number 1 

[ 4.9  3.   1.4  0.2] 0
[ 0.   0.   1.4  0.2] 2
 
 change number 2 

[ 5.1  3.8  1.6  0.2] 0
[ 0.   0.   1.6  0.2] 2
 
 change number 3 

[ 5.   3.4  1.5  0.2] 0
[ 0.   0.   1.5  0.2] 2
 
 change number 4 

[ 5.4  3.7  1.5  0.2] 0
[ 0.   0.   1.5  0.2] 2
 
 change number 5 

[ 4.3  3.   1.1  0.1] 0
[ 0.   0.   1.1  0.1] 2
 
 change number 6 

[ 5.7  4.4  1.5  0.4] 0
[ 0.   0.   1.5  0.4] 2
 
 change number 7 

[ 5.2  3.5  1.5  0.2] 0
[ 0.   0.   1.5  0.2] 2
 
 change number 8 

[ 5.   3.5  1.6  0.6] 0
[ 0.   0.   1.6  0.6] 2
 
 change number 9 

[ 4.6  3.4  1.4  0.3] 0
[ 0.   0.   1.4  0.3] 2
 
 change number 10 

[ 5.1  3.4  1.5  0.2] 0
[ 0.   0.   1.5  0.2] 2
 
 change number 11 

[ 4.9  3.1  1.5  0.1] 0
[ 0.   0.   1.5  0.1] 2
 
 change number 12 

[ 5.4  3.4  1.5  0.4] 0
[ 0.   0.   1.5  0.4] 2
 
 change number 13 

[ 5.   3.6  1.4  0.2] 0
[ 0.   

array([[16,  0, 18],
       [ 0, 27, 18],
       [ 0, 15, 26]])