#### Data source :https://archive.ics.uci.edu/ml/machine-learning-databases/00228/

In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer


/home/milad/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
from butterfingers import butterfinger

add the typo when we have the spam

In [3]:
df=pd.read_csv("../../datasets/SMSSpamCollection",sep='\t',names=['Status','Message'])
print(df.head())


  Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...


In [4]:
for i in  range(df.count()[0]):
    x = df['Status'][i]
    if x=="spam":
        df.loc[i,'Message']=butterfinger(df['Message'][i])



print(df.head())

  Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Xrdg ennry ng 2 a wnon cimp to wnj WE Cyp fmna...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...


In [5]:
len(df)

5572

In [6]:
len(df[df.Status=='spam'])

747

In [7]:
len(df[df.Status=='ham'])

4825

In [8]:
df.loc[df["Status"]=='ham',"Status",]=1

In [9]:
df.loc[df["Status"]=='spam',"Status",]=0

In [10]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Xrdg ennry ng 2 a wnon cimp to wnj WE Cyp fmna...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [11]:
df_x=df["Message"]
df_y=df["Status"]

In [12]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [13]:
x_train.head()

1457    U sleeping now.. Or you going to take? Haha.. ...
472     How long has it been since you screamed, princ...
2481    Uscenv! dxoo 09066612661 hrli mdndmpje. Jolr s...
243     Okay. No no, just shining on. That was meant t...
1413    Wen ur lovable bcums angry wid u, dnt take it ...
Name: Message, dtype: object

In [14]:
cv1 = TfidfVectorizer(min_df=1,stop_words='english')

In [15]:
x_traincv=cv1.fit_transform(x_train)

In [16]:
a=x_traincv.toarray()

In [17]:
a[0]

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [18]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'online',
        'replying', 'sleeping', 'spys', 'wat'],
       dtype='<U27')]

In [19]:
x_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

In [20]:
x_testcv=cv1.transform(x_test)

In [21]:
x_testcv.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [22]:
 mnb = MultinomialNB()

In [23]:
y_train=y_train.astype('int')

In [24]:
y_train

1457    1
472     1
2481    0
243     1
1413    1
2726    1
3184    1
2308    0
2106    1
1473    1
3813    1
5394    1
4308    1
1009    1
3933    1
2759    1
2355    1
4664    1
1719    1
2236    1
570     1
2626    0
2339    1
874     1
354     1
2652    1
1901    1
2673    1
1670    1
4310    1
       ..
3394    1
3633    1
3720    0
1054    1
5493    1
4270    1
4802    1
56      0
2470    1
3785    1
149     1
2581    0
4279    1
1024    1
1411    1
1588    1
5246    1
946     1
5433    1
5047    1
2871    0
3678    1
1082    1
4489    1
456     1
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int64

In [25]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [26]:
testmessage=x_test.iloc[0]

In [27]:
testmessage

'somewhere out there beneath the pale moon light someone think in of u some where out there where dreams come true... goodnite &amp; sweet dreams'

In [28]:
predictions=mnb.predict(x_testcv[0])

In [29]:
predictions

array([1])

In [30]:
a=np.array(y_test)

In [31]:
a

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [32]:
count=0

In [33]:
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1

In [34]:
count

1

In [35]:
len(predictions)

1

In [ ]:
1/1