# load the data and first test the base line 

In [1]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import random
import numpy as np

/home/milad/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
# save "bunch" object containing iris dataset and its attributes
iris = load_iris()
type(iris)

# print the iris data
print(iris.data)


# print the iris data
# print(iris.data)


# print the names of the four features
print(iris.feature_names)


# print integers representing the species of each observation# print 
print(iris.target)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [3]:
# print the encoding scheme for species: 0 = setosa, 1 = versicolor, 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [4]:
# store feature matrix in "X"# store  
X = iris.data

# store response vector in "y"
y = iris.target

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [6]:
mnb = MultinomialNB()
mnb.fit(x_train,y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

# result of the model  on test data (First step)

In [7]:
#compute the f1 and accuracy

y_pred=mnb.predict(x_test)

print ("f1 on test data is       {}".format(f1_score(y_test, y_pred, average='macro')))
print ("Accuracy on test data is {}".format(accuracy_score(y_test, y_pred)))


f1 on test data is       0.8095238095238096
Accuracy on test data is 0.8666666666666667


In [8]:
confusion_matrix(y_test, y_pred)

array([[16,  0,  0],
       [ 0,  5,  0],
       [ 0,  4,  5]])

# result model on the same train data

In [10]:
y_pred_train=mnb.predict(x_train)


print ("f1 on same train data is       {}".format(f1_score(y_train, y_pred_train, average='macro')))
print ("Accuracy on same train data is {}".format(accuracy_score(y_train, y_pred_train)))
print("\n" + classification_report(y_train, y_pred_train))


print(confusion_matrix(y_train, y_pred_train))


f1 on same train data is       0.8777540867093107
Accuracy on same train data is 0.875

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        34
          1       0.75      1.00      0.86        45
          2       1.00      0.63      0.78        41

avg / total       0.91      0.88      0.87       120

[[34  0  0]
 [ 0 45  0]
 [ 0 15 26]]


# base line
- change one feature and chek the target (change function)
- change randomly one value and check the target(change random)

In [170]:
change_plan={"key":[[0,1],[2,1]],"number":[3,3]}


In [180]:
def change_baseline(x_train,y_train,percetage,mnb,change_plan):
    number_change = int(percetage/100*x_train.shape[0])
    
    x_train_changed = np.copy(x_train)
    row_history=[]
    try_times = 0
    occurred_change=0
    change_done = False
    
        
    for i in range(len(change_plan["number"])):
        for j in range(change_plan["number"][i]):

            change_done = False
            while (change_done == False):

                #find uniqe row & as same as user request 
                row = random.randint(1, x_train.shape[0]-1)
                try_times = 0
                while (mnb.predict([x_train[row]])[0] !=change_plan["key"][i][0] or row in row_history): #row in row_history or

                    row = random.randint(1, x_train.shape[0]-1)
                    if try_times > len(y_train):
                        print("your request is not possiable")
                        break 
                        
                    try_times = try_times + 1
                if try_times > len(y_train):
                    print("part of your request can't run")
                    break
                    
                row_history.append(row)

                for ii in range(x_train.shape[1]): # range(4)
                    x_train_changed[row][ii] = 0

                    if (change_plan["key"][i][1] == mnb.predict([x_train_changed[row]])):
                        print(x_train[row],mnb.predict([x_train[row]])[0])
                        print(x_train_changed[row],mnb.predict([x_train_changed[row]])[0])
                        occurred_change=occurred_change + 1
                        change_done = True
                        print(" \n change number {} \n".format(occurred_change))
                        break
                    else:
#                         print("this change doesnot run")
                        x_train_changed[row]= np.copy(x_train[row])
                


    return np.copy(x_train_changed)
        

In [181]:
baseline_out=change_baseline(x_test,y_test,20,mnb,change_plan)

[ 4.8  3.4  1.6  0.2] 0
[ 4.8  0.   1.6  0.2] 1
 
 change number 1 

[ 4.5  2.3  1.3  0.3] 0
[ 0.   2.3  1.3  0.3] 1
 
 change number 2 

[ 5.1  3.8  1.5  0.3] 0
[ 5.1  0.   1.5  0.3] 1
 
 change number 3 

[ 7.6  3.   6.6  2.1] 2
[ 7.6  3.   6.6  0. ] 1
 
 change number 4 

[ 6.7  3.3  5.7  2.1] 2
[ 6.7  3.3  5.7  0. ] 1
 
 change number 5 

[ 5.8  2.7  5.1  1.9] 2
[ 5.8  2.7  0.   1.9] 1
 
 change number 6 



In [183]:
y_pred_baseline_changed=mnb.predict(baseline_out)


print ("f1 on same train data is       {}".format(f1_score(y_test, y_pred_baseline_changed, average='macro')))
print ("Accuracy on test data is {}".format(accuracy_score(y_test, y_pred_baseline_changed)))
confusion_matrix(y_test,y_pred_baseline_changed)

f1 on same train data is       0.5867293625914315
Accuracy on test data is 0.6666666666666666


array([[13,  3,  0],
       [ 0,  5,  0],
       [ 0,  7,  2]])

In [184]:
def change(x_train,y_train,percetage,mnb):
    
    number_change = int(percetage/100*x_train.shape[0])
    print(number_change)
    
    x_train_changed = np.copy(x_train)

    for count,ele in enumerate(x_train_changed[:number_change+2]):
        print(x_train[count],y_train[count])
        for i in range(4):
            x_train_changed[count][i] = 0

            if (y_train[count] != mnb.predict([x_train_changed[count]])):
                break
            else:
                x_train_changed[count]= np.copy(x_train[count])

        print(x_train_changed[count],mnb.predict([x_train_changed[count]])[0])
        print(" \n change number {} \n".format(count))

    return np.copy(x_train_changed)

In [186]:
# new=change(x_train,y_train,20.8,mnb)
new=change(x_test,y_test,20,mnb)


# result model on the dirty data (10 %)

In [ ]:
y_pred_train_changed=mnb.predict(new)


# print ("f1 on same train data is       {}".format(f1_score(y_train, y_pred_train_changed, average='macro')))
# print ("Accuracy on same train data is {}".format(accuracy_score(y_train, y_pred_train_changed)))


print ("f1 on same train data is       {}".format(f1_score(y_test, y_pred_train_changed, average='macro')))
print ("Accuracy on test data is {}".format(accuracy_score(y_test, y_pred_train_changed)))
confusion_matrix(y_test, y_pred_train_changed)

In [274]:
change_plan={"key":[[0,1],[2,1]],"number":[3,3]}

In [275]:
def change_random(x_train,y_train,percetage,mnb,change_plan):
    number_change_requested = int(percetage/100*x_train.shape[0])
    
    print("{} percentage error is equal to {} change \n".format(percetage,number_change_requested))
    
    row_history=[]
    col_history=[]
    occurred_change=0
    
    x_train_changed = np.copy(x_train)
    
            
    for i in range(len(change_plan["number"])):
        for j in range(change_plan["number"][i]):

            change_done = False
            while (change_done == False):

                #find uniqe row & as same as user request 
                row = random.randint(1, x_train.shape[0]-1)
                try_times = 0
                while (mnb.predict([x_train[row]])[0] !=change_plan["key"][i][0] or row in row_history): #row in row_history or

                    row = random.randint(1, x_train.shape[0]-1)
                    if try_times > len(y_train):
                        print("your request is not possiable")
                        break 
                        
                    try_times = try_times + 1
                if try_times > len(y_train):
                    print("part of your request can't run")
                    break
                    
                row_history.append(row)
                
                
                while (len(col_history)<=x_train.shape[1]+1):
                    
                    col = random.randint(0,x_train.shape[1]-1)
                    while col in col_history:
                        col = random.randint(0,x_train.shape[1]-1)
                        if (len(col_history)<=x_train.shape[1]+1):
                            break
                    col_history.append(col)
                    x_train_changed[row][col] = 0
                    
                    if (change_plan["key"][i][1] == mnb.predict([x_train_changed[row]])):
                        print(x_train[row],mnb.predict([x_train[row]])[0])
                        print(x_train_changed[row],mnb.predict([x_train_changed[row]])[0])
                        occurred_change=occurred_change + 1
                        change_done = True
                        print(" \n change number {} \n".format(occurred_change))
                        break
                    else:
                        x_train_changed[row]= np.copy(x_train[row])


    return np.copy(x_train_changed)
         



In [291]:
new_random=change_random(x_test,y_test,20,mnb,change_plan)

20 percentage error is equal to 6 change 

[ 4.8  3.4  1.9  0.2] 0
[ 4.8  0.   1.9  0.2] 1
 
 change number 1 

your request is not possiable
part of your request can't run
your request is not possiable
part of your request can't run
your request is not possiable
part of your request can't run
your request is not possiable
part of your request can't run
your request is not possiable
part of your request can't run


# result model on the dirty data (10 %) -random

In [270]:
y_pred_test_changed_random=mnb.predict(new_random)


# print ("f1 on same train data is       {}".format(f1_score(y_train, y_pred_train_changed_random, average='macro')))
# print ("Accuracy on same train data is {}".format(accuracy_score(y_train, y_pred_train_changed_random)))


print ("f1 on same train data is       {}".format(f1_score(y_test, y_pred_test_changed_random, average='macro')))
print ("Accuracy on same train data is {}".format(accuracy_score(y_test, y_pred_test_changed_random)))

f1 on same train data is       0.6506238859180036
Accuracy on same train data is 0.7666666666666667


In [ ]:
confusion_matrix(y_test,y_pred_test_changed_random)

# find the most important features

In [ ]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#knn = KNeighborsClassifier(n_neighbors=4)
mnb2 = MultinomialNB()
# sfs1 = SFS(knn, 
#            k_features=1, 
#            forward=True, 
#            floating=False, 
#            verbose=2,
#            scoring='accuracy',
#            cv=0)
sfs1 = SFS(mnb, 
#            k_features=1, 
           forward=True, 
           floating=False, 
           verbose=2,
           scoring='accuracy',
           cv=0)






sfs1 = sfs1.fit(X, y)

In [ ]:
sfs1.subsets_


# most important feature

In [ ]:
sfs1.k_feature_idx_

In [ ]:
def change_spetial_feature(x_train,y_train,percetage,mnb,feature):
    change_item=0
    number_change_spetial = int(percetage/100*x_train.shape[0])
    print(number_change_spetial)
    
    x_train_changed_spetial = np.copy(x_train)

    for count,ele in enumerate(x_train_changed_spetial):
        

        x_train_changed_spetial[count][feature] = 0

        if (y_train[count] != mnb.predict([x_train_changed_spetial[count]])):
            change_item=change_item+1
            if (change_item < number_change_spetial):

                print(x_train[count],y_train[count])
                print(x_train_changed_spetial[count],mnb.predict([x_train_changed_spetial[count]])[0])
                print(" \n change number {} \n".format(change_item))
            else:

                break
        else:
            x_train_changed_spetial[count]= np.copy(x_train[count])

    return np.copy(x_train_changed_spetial)

In [ ]:
new_random_spetial=change_spetial_feature(x_test,y_test,20,mnb,0)

# result model on the dirty data (10 %) -spetial feature

In [ ]:
y_pred_train_changed_spetial=mnb.predict(new_random_spetial)


# print ("f1 on same train data is       {}".format(f1_score(y_train, y_pred_train_changed_spetial, average='macro')))
# print ("Accuracy on same train data is {}".format(accuracy_score(y_train, y_pred_train_changed_spetial)))

print ("f1 on same train data is       {}".format(f1_score(y_test, y_pred_train_changed_spetial, average='macro')))
print ("Accuracy on same train data is {}".format(accuracy_score(y_test, y_pred_train_changed_spetial)))

In [ ]:
confusion_matrix()

In [ ]:
co=0
for count1,ele1 in enumerate(new_random_spetial):
    if ele1[0]==0:
        co=co+1
        print(new_random_spetial[count1])
print(co)

In [ ]:
def max_indices(arr, k):
    '''
    Returns the indices of the k first largest elements of arr
    (in descending order in values)
    '''
    assert k <= arr.size, 'k should be smaller or equal to the array size'
    arr_ = arr.astype(float)  # make a copy of arr
    max_idxs = []
    for _ in range(k):
        max_element = np.max(arr_)
        if np.isinf(max_element):
            break
        else:
            idx = np.where(arr_ == max_element)
        max_idxs.append([int(idx[0]),int(idx[1])])
        arr_[idx] = -np.inf
    return max_idxs

In [ ]:
array=confusion_matrix(y_train, y_pred_train)
max_indices(array,4)

In [ ]:
import seaborn as sn
import pandas as pd
import matplotlib.pyplot as plt

def change_confuation_matrix(x_train,mnb):
    y_pred_train=mnb.predict(x_train)
    array=confusion_matrix(y_train, y_pred_train)
    
    max_list = max_indices(array,4)
    rong_class= max_list[array.shape[0]]
     
    
    print("the data point of class {} wrongly classify as class {}".format(rong_class[0],rong_class[1]))
    df_cm = pd.DataFrame(array, range(array.shape[0]),range(array.shape[0]))
    
    sn.set(font_scale=1.4)#for label size
    sn.heatmap(df_cm, annot=True,annot_kws={"size": 16})# font size
    

In [ ]:
change_confuation_matrix(x_train,mnb)

In [ ]:
array=confusion_matrix(y_train, y_pred_train)
import itertools

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.figure()
    plt.show()
    
    
    
    
    

class_names = iris.target_names
plot_confusion_matrix(array, classes=class_names,
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(array, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

