In [1]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris

In [2]:
# save "bunch" object containing iris dataset and its attributes
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
# print the iris data
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [4]:
# print the names of the four features
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
# print integers representing the species of each observation# print 
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
# print the encoding scheme for species: 0 = setosa, 1 = versicolor, 2 = virginica
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [33]:
# store feature matrix in "X"# store  
X = iris.data

# store response vector in "y"
y = iris.target

In [8]:
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import f1_score
import random
import numpy as np

/home/milad/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [34]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

In [10]:
mnb = MultinomialNB()
mnb.fit(x_train,y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [11]:
y_pred=mnb.predict(x_test)

In [12]:
f1_score(y_test, y_pred, average='macro')

0.80952380952380965

In [13]:
y_pred_train=mnb.predict(x_train)
f1_score(y_train, y_pred_train, average='macro')

0.87775408670931065

In [ ]:
np.random.randint(4, size=10)

In [32]:
def changed2(x_train,y_train,percetage,mnb):
    
    number_change = int(percetage/100*x_train.shape[0])
    x_train_changed = x_train
    result=[]
    print(number_change)
    for i in range(number_change):
        p=1
        print(x_train[i],y_train[i])
        while (y_train[i] == mnb.predict([x_train_changed[i]])):
            x_train_changed[i][p-1]= x_train[i][p-1]
            x_train_changed[i][p]= 0
            p= p+1
            if p>=1:
                x_train_changed[i][p-1]= x_train[i][p-1]
                print("hahahah")
                print(x_train_changed[i])
        print(x_train_changed[i],mnb.predict([x_train_changed[i]])[0])                
        print("@@@@@@@@@@@@@@@@@@@@")
    return x_train_changed
                                         

In [76]:
def change_random(x_train,y_train,percetage,mnb):
    
    value_selector_history=[]
    col_history=[]
    number_change = int(percetage/100*x_train.shape[0])
    x_train_changed = x_train
    
    
    for i in range(number_change):
              
        row = random.randint(1, x_train.shape[0])
        col = random.randint(0,x_train.shape[1]-1)

        while (row in value_selector_history) or (col in col_history):
            
            row = random.randint(1, x_train.shape[0])
            col = random.randint(0,x_train.shape[1]-1)
        value_selector_history.append(row)
        col_history.append(col)


        print("row {}   value {} {}".format(row,x_train[row],y_train[row]))
        while(y_train[row] == mnb.predict([x_train_changed[row]])):
            x_train_changed[row] = x_train[row]
            x_train_changed[row][col]=0
            col = random.randint(0,x_train.shape[1]-1)
                
#             if (y_train[row] == mnb.predict([x_train_changed[row]])):
#                 col = random.randint(0,x_train.shape[1]-1)
            
        print("row {}   value {} {}".format(row,x_train_changed[row],mnb.predict([x_train_changed[row]])[0]))
        print('"""""""""""""""""')
        col_history=[]

         



In [82]:
change_random(x_train,y_train,10,mnb)

row 70   value [ 6.8  2.8  0.   1.4] 1
row 70   value [ 6.8  2.8  0.   1.4] 0
"""""""""""""""""
row 1   value [ 4.6  3.2  1.4  0.2] 0
row 1   value [ 4.6  0.   1.4  0.2] 1
"""""""""""""""""
row 75   value [ 5.5  2.4  0.   1. ] 1
row 75   value [ 5.5  2.4  0.   1. ] 0
"""""""""""""""""
row 76   value [ 0.  0.  0.  0.] 0
row 76   value [ 0.  0.  0.  0.] 1
"""""""""""""""""
row 99   value [ 6.3  0.   4.7  1.6] 1
row 99   value [ 6.3  0.   4.7  1.6] 2
"""""""""""""""""
row 46   value [ 6.5  2.8  4.6  1.5] 1
row 46   value [ 6.5  2.8  0.   1.5] 0
"""""""""""""""""
row 77   value [ 6.7  3.   0.   2.3] 2
row 77   value [ 6.7  3.   0.   2.3] 1
"""""""""""""""""
row 22   value [ 7.7  2.6  6.9  2.3] 2
row 22   value [ 7.7  2.6  0.   2.3] 1
"""""""""""""""""
row 89   value [ 6.4  3.2  5.3  2.3] 2
row 89   value [ 6.4  3.2  0.   2.3] 1
"""""""""""""""""
row 74   value [ 5.5  2.5  4.   1.3] 1
row 74   value [ 5.5  2.5  0.   1.3] 0
"""""""""""""""""
row 58   value [ 0.  0.  0.  0.] 2
row 58   value 

In [31]:
x_train_changed=changed2(x_train,y_train,10,mnb)

12
[ 5.4  3.   4.5  1.5] 1
hahahah
[ 0.   3.   4.5  1.5]
[ 0.   3.   4.5  1.5] 2
@@@@@@@@@@@@@@@@@@@@
[ 4.6  3.2  1.4  0.2] 0
hahahah
[ 0.   3.2  1.4  0.2]
hahahah
[ 0.   0.   1.4  0.2]
[ 0.   0.   1.4  0.2] 2
@@@@@@@@@@@@@@@@@@@@
[ 6.7  2.5  5.8  1.8] 2
hahahah
[ 0.   2.5  5.8  1.8]
hahahah
[ 0.   0.   5.8  1.8]
hahahah
[ 0.   0.   0.   1.8]
hahahah
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.] 1
@@@@@@@@@@@@@@@@@@@@
[ 4.9  3.   1.4  0.2] 0
hahahah
[ 0.   3.   1.4  0.2]
hahahah
[ 0.   0.   1.4  0.2]
[ 0.   0.   1.4  0.2] 2
@@@@@@@@@@@@@@@@@@@@
[ 5.   2.3  3.3  1. ] 1
hahahah
[ 0.   2.3  3.3  1. ]
[ 0.   2.3  3.3  1. ] 2
@@@@@@@@@@@@@@@@@@@@
[ 6.7  3.3  5.7  2.5] 2
hahahah
[ 0.   3.3  5.7  2.5]
hahahah
[ 0.   0.   5.7  2.5]
hahahah
[ 0.   0.   0.   2.5]
hahahah
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.] 1
@@@@@@@@@@@@@@@@@@@@
[ 7.2  3.2  6.   1.8] 2
[ 7.2  3.2  6.   1.8] 1
@@@@@@@@@@@@@@@@@@@@
[ 5.8  2.6  4.   1.2] 1
hahahah
[ 0.   2.6  4.   1.2]
[ 0.   2.6  4.   1.2] 2
@@@@@@@@@@@@@@@@@@@@
[ 6.7  3.1 

In [26]:
y_pred_train=mnb.predict(x_train)
f1_score(y_train, y_pred_train, average='macro')

0.78828347578347591

In [19]:
y_pred1=mnb.predict(x_train_changed)
f1_score(y_train, y_pred1, average='macro')

0.78828347578347591

In [20]:
y_pred2=mnb.predict(x_test)
f1_score(y_test, y_pred2, average='macro')

0.80952380952380965

In [21]:
x_test_changed=changed2(x_test,y_test,10,mnb)

3
[ 6.4  2.8  5.6  2.1] 2
[ 0.  0.  0.  0.] 1
@@@@@@@@@@@@@@@@@@@@
[ 5.7  3.8  1.7  0.3] 0
[ 0.   0.   1.7  0.3] 2
@@@@@@@@@@@@@@@@@@@@
[ 7.4  2.8  6.1  1.9] 2
[ 7.4  2.8  6.1  1.9] 1
@@@@@@@@@@@@@@@@@@@@


In [22]:
y_pred3=mnb.predict(x_test_changed)
f1_score(y_test, y_pred3, average='macro')

0.73527905785970304